interval: 10 # Interval between pollings
loglevel: 4 # 1-5
concurrent_limit: 5
# Prometheus metrics are exposed at http://exporter_address/metrics
exporter_address: :8081

# Address where JSON API will be served
json_api:
  address: :7001

checkpoint: /data/checkpoint.json

dummy:
  oneshot_common: &oneshot_common
    retry: 5
    retry_interval: 60

repos:
  - type: shell_script
    script: /worker-script/rsync.sh
    source: rsync://rsync.chiark.greenend.org.uk/ftp/users/sgtatham/putty-website-mirror/
    interval: 3600
    path: /mnt/putty
    name: putty
    <<: *oneshot_common
  - type: shell_script
    name: archlinux-cn
    interval: 6000
    path: /mnt/archlinux-cn
    script: /worker-script/zhiyuan/worker-script/archlinux-cn.sh
    <<: *oneshot_common
  - type: shell_script
    script: /worker-script/rsync.sh
    source: rsync://mirrors.dotsrc.org/archlinuxarm/
    interval: 3900
    path: /mnt/archlinuxarm
    name: archlinuxarm
    exclude_hidden: true
  - type: shell_script
    script: /worker-script/rsync.sh
    source: rsync://rsync11.us.gentoo.org/gentoo-portage/
    interval: 3600
    path: /mnt/gentoo
    name: gentoo
    <<: *oneshot_common
  - type: shell_script
    script: /worker-script/rsync.sh
    source: rsync://ftp.ca.vim.org/vim
    interval: 3600
    path: /mnt/vim
    name: vim
    <<: *oneshot_common
  - type: shell_script
    script: /worker-script/rsync.sh
    source: rsync://rsync.alpinelinux.org/alpine/
    interval: 3600
    path: /mnt/alpine
    name: alpine
    no_redir_http: true
    <<: *oneshot_common
  - type: shell_script
    script: /worker-script/rsync.sh
    source: cpan-rsync.perl.org::CPAN
    interval: 3600
    path: /mnt/cpan
    name: cpan
    <<: *oneshot_common
  - type: shell_script
    script: /worker-script/zhiyuan/worker-script/rsync_ssh.sh
    source: "cran-rsync@cran.r-project.org:"
    interval: 43200
    path: /mnt/cran
    name: cran
    ignore_vanish: true
    <<: *oneshot_common
  - type: shell_script
    script: /worker-script/rsync.sh
    source: rsync://mirrors.tuna.tsinghua.edu.cn/ctex/
    interval: 3600
    path: /mnt/ctex
    name: ctex
    <<: *oneshot_common
  - type: shell_script
    script: /worker-script/rsync.sh
    source: rsync://mirrors.ocf.berkeley.edu/gnu/
    interval: 43200
    path: /mnt/gnu
    name: gnu
    <<: *oneshot_common
  - type: shell_script
    script: /worker-script/rsync.sh
    source: rsync://mirror.steadfast.net/cygwin/
    interval: 3600
    path: /mnt/cygwin
    name: cygwin
    <<: *oneshot_common
  - type: shell_script
    script: /worker-script/zhiyuan/worker-script/rsync.sh
    source: rsync.osuosl.org::ros-main
    interval: 3600
    path: /mnt/ros
    mirror_path: /mnt/ros/ubuntu
    name: ros
    <<: *oneshot_common
  - type: shell_script
    script: /worker-script/rsync.sh
    source: rsync://ftp.nluug.nl/kali/
    interval: 10800
    path: /mnt/kali
    name: kali
    <<: *oneshot_common
  - type: shell_script
    script: /worker-script/rsync.sh
    source: rsync://ftp.nluug.nl/kali-images/
    interval: 10800
    path: /mnt/kali-images
    name: kali-images
    <<: *oneshot_common
  - type: shell_script
    script: /worker-script/zhiyuan/worker-script/git.sh
    name: git/homebrew-core.git
    origin: https://github.com/Homebrew/homebrew-core.git
    interval: 3801
    path: /mnt/git/homebrew-core.git
    target: https://git.sjtu.edu.cn/sjtug/homebrew-core.git
    serve_mode: git
    <<: *oneshot_common
  - type: shell_script
    script: /worker-script/zhiyuan/worker-script/git.sh
    name: git/homebrew-cask.git
    interval: 3801
    path: /mnt/git/homebrew-cask.git
    origin: https://github.com/Homebrew/homebrew-cask.git
    target: https://git.sjtu.edu.cn/sjtug/homebrew-cask.git
    serve_mode: git
    <<: *oneshot_common
  - type: shell_script
    script: /worker-script/zhiyuan/worker-script/git.sh
    name: git/brew.git
    interval: 3927
    path: /mnt/git/brew.git
    origin: https://github.com/Homebrew/brew.git
    target: https://git.sjtu.edu.cn/sjtug/brew.git
    serve_mode: git
    <<: *oneshot_common
  - type: shell_script
    script: /worker-script/zhiyuan/worker-script/crates-io.sh
    name: git/crates.io-index
    interval: 3601
    path: /mnt/git/crates.io-index
    origin: https://github.com/rust-lang/crates.io-index.git
    target: https://git.sjtu.edu.cn/sjtug/crates.io-index.git
    serve_mode: git
    <<: *oneshot_common
  - type: shell_script
    name: raspbian
    script: /worker-script/rsync.sh
    path: /mnt/raspbian
    interval: 10801
    source: rsync://mirrors.tuna.tsinghua.edu.cn/raspbian/
    no_redir_http: true
    <<: *oneshot_common
  - type: shell_script
    name: parrot
    script: /worker-script/rsync.sh
    path: /mnt/parrot
    interval: 3802
    source: rsync://archive.parrotsec.org:/parrot
    <<: *oneshot_common
  - type: shell_script
    name: raspberrypi
    script: /worker-script/rsync.sh
    path: /mnt/raspberrypi
    interval: 10801
    source: apt-repo.raspberrypi.org::archive
    <<: *oneshot_common
  - type: shell_script
    name: mx-isos
    script: /worker-script/rsync_password.sh
    path: /mnt/mx-isos
    interval: 43301
    source: downstreamtestuser@rsync-mxlinux.org::MX-Linux/
    # Password is made public at https://mxlinux.org/wiki/rsyncserver/mirroring-mx-antix-linux/
    # So we do not hide it behind secrets
    password: dstuPwd
    <<: *oneshot_common
  - type: shell_script
    name: mx-packages
    script: /worker-script/rsync_password.sh
    path: /mnt/mx-packages
    interval: 9602
    source: rsuser@iso.mxrepo.com::workspace
    # Password is made public at https://mxlinux.org/wiki/rsyncserver/mirroring-mx-antix-linux/
    # So we do not hide it behind secrets
    password: T1tpw4rstmr
    <<: *oneshot_common
  - type: shell_script
    script: /worker-script/zhiyuan/worker-script/packagist.sh
    interval: 4800
    path: /mnt/packagist
    name: packagist
    subdomain: packagist.mirrors.sjtug.sjtu.edu.cn
    upstream: https://repo.packagist.org
    <<: *oneshot_common
  - type: shell_script
    script: /worker-script/zhiyuan/worker-script/mongodb.sh
    source: s3://repo.mongodb.org/
    interval: 4600
    path: /mnt/mongodb
    name: mongodb
    <<: *oneshot_common
  - type: shell_script
    script: /worker-script/rsync.sh
    source: master.qt.io::qt-all
    interval: 6000
    path: /mnt/qt
    name: qt
    rsync_extra_flags: --exclude "snapshots/*"
    no_redir_http: true
  - type: shell_script
    script: julia -t auto /worker-script/zhiyuan/worker-script/julia.jl
    interval: 8000
    path: /mnt/julia
    name: julia
  - type: shell_script
    name: emacs-elpa
    script: /worker-script/zhiyuan/worker-script/emacs-elpa.sh
    path: /mnt/emacs-elpa
    interval: 5000
    source: rsync://elpa.emacs-china.org/elpa/
  - type: shell_script
    script: /worker-script/zhiyuan/worker-script/julia-releases.sh
    source: s3://julialang2/
    interval: 9200
    path: /mnt/julia-releases
    name: julia-releases
    <<: *oneshot_common
  - type: shell_script
    name: raspberry-pi-os-images
    script: /worker-script/rsync.sh
    path: /mnt/raspberry-pi-os-images
    interval: 10801
    source: rsync://mirrors.tuna.tsinghua.edu.cn/raspberry-pi-os-images/
    <<: *oneshot_common
  - type: shell_script
    name: msys2
    script: /worker-script/rsync.sh
    path: /mnt/msys2
    interval: 12001
    source: rsync://repo.msys2.org/builds
    <<: *oneshot_common
  - type: shell_script
    script: /worker-script/zhiyuan/worker-script/opam.sh
    name: git/opam-repository.git
    interval: 4623
    path: /mnt/git/opam-repository.git
    origin: https://github.com/ocaml/opam-repository.git
    target: https://git.sjtu.edu.cn/sjtug/opam-repository.git
    serve_mode: git
    <<: *oneshot_common
  - type: shell_script
    script: /worker-script/zhiyuan/worker-script/git.sh
    name: git/qemu.git
    origin: https://git.qemu.org/git/qemu.git
    interval: 4300
    path: /mnt/git/qemu.git
    target: https://git.sjtu.edu.cn/sjtug/qemu.git
    serve_mode: git
    <<: *oneshot_common
  - type: shell_script
    script: /worker-script/zhiyuan/worker-script/git.sh
    name: git/linux.git
    origin: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git
    interval: 4700
    path: /mnt/git/linux.git
    target: https://git.sjtu.edu.cn/sjtug/linux.git
    serve_mode: git
    <<: *oneshot_common
  - type: shell_script
    script: /worker-script/rsync.sh
    source: rsync://repo.linuxliteos.com/repo
    interval: 7200
    path: /mnt/linuxliteos
    name: linuxliteos
    <<: *oneshot_common
  - type: shell_script
    name: download.flutter.io
    script: /worker-script/rsync.sh
    path: /mnt/download.flutter.io
    interval: 7200
    source: rsync://mirrors.tuna.tsinghua.edu.cn/flutter/download.flutter.io/
    <<: *oneshot_common
  - type: external
    name: k8s.gcr.io
    proxy_to: https://k8s-gcr-io.siyuan.internal.sjtug.org
    subdomain: k8s-gcr-io.mirrors.sjtug.sjtu.edu.cn
    unified: disable
    serve_mode: proxy
  - type: external
    name: docker-registry
    proxy_to: https://docker.siyuan.internal.sjtug.org
    subdomain: docker.mirrors.sjtug.sjtu.edu.cn
    unified: disable
    serve_mode: proxy
  - type: external
    name: google-fonts
    subdomain: google-fonts.mirrors.sjtug.sjtu.edu.cn
    serve_mode: redir
    target: https://fonts.googleapis.com
    disabled: true
  - type: external
    name: CPAN
    path: /mnt/CPAN
    disabled: true
  - type: external
    name: CRAN
    path: /mnt/CRAN
    disabled: true
  - type: shell_script
    script: /worker-script/anaconda.sh --workers 4 --s3-buffer-path /var/cache --print-plan 100 --no-delete --concurrent-transfer 64
    serve_mode: mirror_intel
    interval: 3600
    name: anaconda
    subdomain: anaconda.mirrors.sjtug.sjtu.edu.cn
    <<: *oneshot_common
  - type: external
    name: CTAN
    path: /mnt/CTAN
    disabled: true
  - type: shell_script
    script: /worker-script/rsync.sh
    source: rsync://rsync.dante.ctan.org/CTAN
    interval: 23020
    path: /mnt/ctan
    no_redir_http: true
    name: ctan
    <<: *oneshot_common
