services:
  frontend:
    build:
      args:
        - SITE_NAME=Zhiyuan
    container_name: zhiyuan-frontend
    mem_limit: 1G
    memswap_limit: 1G

  caddy:
    container_name: zhiyuan-caddy
    volumes:
      - "/mnt/data12T:/mnt:ro"
      - "./caddy/Caddyfile.zhiyuan:/etc/caddy/Caddyfile:ro"
    mem_limit: 30G
    memswap_limit: 30G

  lug:
    container_name: zhiyuan-lug
    volumes:
      - "/mnt/data12T:/mnt"
      - "./config.zhiyuan.yaml:/config.yaml:ro"
    environment:
      MIRROR_CLONE_SITE: "mirrors.sjtug.sjtu.edu.cn"
    mem_limit: 10G
    memswap_limit: 10G

  rsync-gateway:
    container_name: zhiyuan-rsync-gateway
    volumes:
      - "./rsync-gateway/config.zhiyuan.toml:/app/config.toml:ro"
    mem_limit: 5G
    memswap_limit: 5G

  postgres:
    container_name: zhiyuan-postgres
    volumes:
      - "./postgresql.zhiyuan.conf:/etc/postgresql/postgresql.conf:ro"
      - "/mnt/data12T/postgres-data:/var/lib/postgresql/data"
    mem_limit: 10G
    memswap_limit: 10G

  cadvisor:
    container_name: zhiyuan-cadvisor

  clash:
    container_name: zhiyuan-clash

  mirror-intel:
    container_name: zhiyuan-mirror-intel
    volumes:
      - "/mnt/cache:/mnt/cache"
    mem_limit: 10G
    memswap_limit: 10G

  tunnel:
    container_name: zhiyuan-tunnel
    restart: unless-stopped
    image: teddysun/xray
    expose:
      - 5000
      - 5001
      - 5002
      - 5006
    ports:
      - "127.0.0.1:5000:5000"
    networks:
      - tunnel-net
    volumes:
      - "./secrets/xray.json:/etc/xray/config.json:z,ro"
    logging:
      options:
        max-size: "4M"
        max-file: "20"
    ulimits:
      nofile:
        soft: 80000
        hard: 120000
    mem_limit: 2G
    memswap_limit: 2G

  rsyncd:
    container_name: zhiyuan-rsyncd
    volumes:
      - ./rsyncd/rsyncd.zhiyuan.conf:/etc/rsyncd.conf:ro
      - /mnt/data12T:/mnt:ro
      - ./rsyncd/motd.zhiyuan:/etc/rsync/motd:ro
    blkio_config:
      weight: 10
      device_read_bps:
        - path: /dev/mapper/vg0-mirror.sjtug
          rate: "10mb"
      device_read_iops:
        - path: /dev/mapper/vg0-mirror.sjtug
          rate: 20

  git-backend:
    container_name: zhiyuan-git-backend
    volumes:
      - "/mnt/data12T/git:/git:z"
    mem_limit: 1G
    memswap_limit: 1G

  k8s-registry:
    container_name: zhiyuan-k8s-registry
    restart: unless-stopped
    image: registry:2.8
    networks:
      - ipv6-service-net
      - proxy-net
    expose:
      - 80
      - 5001
    volumes:
      - "./secrets/k8s-registry.yml:/etc/docker/registry/config.yml"
    environment:
      http_proxy: http://clash:8080
      https_proxy: http://clash:8080
      HTTP_PROXY: http://clash:8080
      HTTPS_PROXY: http://clash:8080
    logging:
      options:
        max-size: "4M"
        max-file: "20"
    ulimits:
      nofile:
        soft: 80000
        hard: 120000
    mem_limit: 5G
    memswap_limit: 5G

  docker-registry:
    container_name: zhiyuan-docker-registry
    restart: unless-stopped
    image: registry:2.8
    networks:
      - ipv6-service-net
      - proxy-net
    expose:
      - 80
      - 5001
    volumes:
      - "./secrets/docker-registry.yml:/etc/docker/registry/config.yml"
    environment:
      http_proxy: http://clash:8080
      https_proxy: http://clash:8080
      HTTP_PROXY: http://clash:8080
      HTTPS_PROXY: http://clash:8080
    logging:
      options:
        max-size: "4M"
        max-file: "20"
    ulimits:
      nofile:
        soft: 80000
        hard: 120000
    mem_limit: 5G
    memswap_limit: 5G

networks:
  host-monitor-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.31.0.0/16
  monitor-net:
  tunnel-net:
  proxy-net:
  ipv6-service-net:
    enable_ipv6: true
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: fd01::/80
