services:
  frontend:
    build:
      args:
        - SITE_NAME=Siyuan
    container_name: siyuan-frontend
    mem_limit: 1G
    memswap_limit: 1G

  caddy:
    container_name: siyuan-caddy
    volumes:
      - "/mnt/data32T:/srv/data32T:ro"
      - "./caddy/Caddyfile.siyuan:/etc/caddy/Caddyfile:ro"
      - "/etc/ssl/certs/ftp_sjtu:/etc/ssl/certs/ftp_sjtu:ro"
    mem_limit: 20G
    memswap_limit: 20G

  lug:
    container_name: siyuan-lug
    volumes:
      - "/mnt/data32T:/srv/data32T"
      - "./config.siyuan.yaml:/config/0-base.yaml:ro"
      - "./secrets/secrets.siyuan.yaml:/config/99-secrets.yaml:ro"
    environment:
      MIRROR_CLONE_SITE: "mirror.sjtu.edu.cn"
    mem_limit: 30G
    # memswap_limit: 20G

  rsync-gateway:
    container_name: siyuan-rsync-gateway
    volumes:
      - "./rsync-gateway/config.siyuan.toml:/app/config.toml:ro"
    mem_limit: 5G
    memswap_limit: 5G

  postgres:
    container_name: siyuan-postgres
    volumes:
      - './postgresql.siyuan.conf:/etc/postgresql/postgresql.conf:ro'
      - "/mnt/data32T/postgres-data:/var/lib/postgresql/data"
    mem_limit: 30G
    memswap_limit: 30G

  logspout:
    container_name: siyuan-logspout
    command: syslog+tcp://tunnel:5004

  cadvisor:
    container_name: siyuan-cadvisor

  clash:
    container_name: siyuan-clash
    ports:
      - 127.0.0.1:8080:8080

  mirror-intel:
    container_name: siyuan-mirror-intel
    volumes:
      - "/mnt/data32T/mirror-intel-cache:/mnt/cache"
    mem_limit: 15G
    memswap_limit: 15G

  tunnel:
    container_name: siyuan-tunnel
    restart: unless-stopped
    image: v2ray/official
    expose:
      - 5003
      - 5004
      - 5005
      - 5007
    ports:
      - "127.0.0.1:5005:5005"
    networks:
      - tunnel-net
    volumes: 
      - "./secrets/v2ray.json:/etc/v2ray/config.json:z,ro"
    logging:
      options:
        max-size: "4M"
        max-file: "20"
    ulimits:
      nofile:
        soft: 80000
        hard: 120000
    mem_limit: 2G
    memswap_limit: 2G

  rsyncd:
    container_name: siyuan-rsyncd
    volumes:
      - ./rsyncd/rsyncd.siyuan.conf:/etc/rsyncd.conf:ro
      - /mnt/data32T:/srv/data32T:ro
      - ./rsyncd/motd.siyuan:/etc/rsync/motd:ro
    blkio_config:
      weight: 10
      device_read_bps:
        - path: /dev/vdb
          rate: '10mb'
      device_read_iops:
        - path: /dev/vdb
          rate: 20

  git-backend:
    container_name: siyuan-git-backend
    volumes:
      - "/mnt/data32T/git:/git:z"
    mem_limit: 1G
    memswap_limit: 1G

networks:
  host-monitor-net:
    driver: bridge
    ipam:
      driver: default
      config:
      -  subnet: 172.31.0.0/16
    driver_opts:
      com.docker.network.driver.mtu: 1450
  monitor-net:
    driver_opts:
      com.docker.network.driver.mtu: 1450
  tunnel-net:
    driver_opts:
      com.docker.network.driver.mtu: 1450
  proxy-net:
    driver_opts:
      com.docker.network.driver.mtu: 1450
  ipv6-service-net:
    enable_ipv6: true
    driver: bridge
    ipam:
      driver: default
      config:
      -  subnet: fd01::/80
    driver_opts:
      com.docker.network.driver.mtu: 1450
