bind = ["0.0.0.0:8000"]
s3_url = "https://s3.jcloud.sjtu.edu.cn"
s3_region = "sjtug"
database_url = "postgres://rsync-sjtug@postgres/rsync-sjtug"

[log]
format = "json"
target = "tcp://tunnel:5006"

[endpoints.kali-images]
namespace = "kali-images"
s3_bucket = "899a892efef34b1b944a19981040f55b-oss01"
s3_prefix = "rsync/kali-images"

[endpoints.raspbian]
namespace = "raspbian"
s3_bucket = "899a892efef34b1b944a19981040f55b-oss01"
s3_prefix = "rsync/raspbian"

[endpoints.parrot]
namespace = "parrot"
s3_bucket = "899a892efef34b1b944a19981040f55b-oss01"
s3_prefix = "rsync/parrot"

[endpoints.raspberrypi]
namespace = "raspberrypi"
s3_bucket = "899a892efef34b1b944a19981040f55b-oss01"
s3_prefix = "rsync/raspberrypi"

[endpoints.msys2]
namespace = "msys2"
s3_bucket = "899a892efef34b1b944a19981040f55b-oss01"
s3_prefix = "rsync/msys2"
